# Generated by Django 6.0 on 2026-01-30 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_uz", models.CharField(max_length=255)),
                ("name_ru", models.CharField(blank=True, max_length=255, null=True)),
                ("desc_uz", models.TextField(blank=True, null=True)),
                ("desc_ru", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=1)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("file", models.FileField(blank=True, null=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_uz", models.CharField(max_length=255)),
                ("name_ru", models.CharField(blank=True, max_length=255, null=True)),
                ("desc_uz", models.TextField(blank=True, null=True)),
                ("desc_ru", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_uz", models.CharField(max_length=255)),
                ("name_ru", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_uz", models.CharField(max_length=255)),
                ("name_ru", models.CharField(blank=True, max_length=255, null=True)),
                ("desc_uz", models.TextField(blank=True, null=True)),
                ("desc_ru", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=1)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("file", models.FileField(blank=True, null=True, upload_to="")),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homeworks",
                        to="teacher.lesson",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lesson",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="teacher.section"
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="subjects",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="teacher.subject"
            ),
        ),
        migrations.CreateModel(
            name="Submittion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("ball", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("file", models.FileField(blank=True, null=True, upload_to="")),
                (
                    "homework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="teacher.homework",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="student.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salary", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ishlayapti", "Ishlayapti"),
                            ("ishdan_chiqib_ketgan", "Ishdan Chiqib Ketgan"),
                            ("tatilda", "Tatilda"),
                            ("dekretda", "Dekretda"),
                            ("chetlashtirilgan", "Chetlashtirilgan"),
                        ],
                        default="ishlayapti",
                        max_length=20,
                    ),
                ),
                ("is_support", models.BooleanField(default=False)),
                ("expirience", models.IntegerField(default=0)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="subjects",
                        to="teacher.subject",
                    ),
                ),
            ],
        ),
    ]
