# Generated by Django 6.0 on 2026-01-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("group", "0001_initial"),
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="students",
            field=models.ManyToManyField(blank=True, to="student.student"),
        ),
    ]
