# Generated by Django 6.0 on 2026-01-30 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("group", "0002_initial"),
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groups",
                to="teacher.subject",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="groups",
                to="teacher.teacher",
            ),
        ),
    ]
