# Generated by Django 6.0 on 2026-01-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("yangi", "Yangi"),
                            ("oqimoqda", "Oqimoqda"),
                            ("tugatgan", "Tugatgan"),
                            ("chiqib ketgan", "Chiqib Ketgan"),
                            ("chetlashtirilgan", "Chetlashtirilgan"),
                        ],
                        default="yangi",
                        max_length=20,
                    ),
                ),
                ("coin", models.IntegerField(default=0)),
                ("wallet", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="StudentAttandance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_status",
                    models.CharField(
                        choices=[
                            ("here", "Here"),
                            ("kelmagan", "Absent"),
                            ("cause_absent", "Cause Absent"),
                        ],
                        default="kelmagan",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("ball", models.PositiveIntegerField(default=0)),
                ("comment", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
